/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Dao.DiaDiemDieuTriDao;
import Dao.NhanVienDao;
import Dao.TaiKhoanDao;
import Objects.DiaDiem;
import Objects.NhanVien;
import java.awt.event.ItemEvent;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;


public class QuanLyNhanVien extends javax.swing.JFrame {

    /**
     * Creates new form SellForm
     */
    List<NhanVien> nvList = new ArrayList<>();
    DefaultTableModel tableModel;
    ArrayList<String> ddList = new ArrayList<>();
    
    public QuanLyNhanVien() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        tableModel = (DefaultTableModel) tblDanhSach.getModel();
        getData();
        btnSua.setEnabled(false);
        btnXoa.setEnabled(false);
//        trangThaiVar.setEnabled(false);
        lichSuCovidVar.setText("Có");
        lichSuCovidVar.setEnabled(false);
        checkAddress();
    }

    public void getData(){
        nvList = NhanVienDao.getAll();
        tableModel.setRowCount(0);
        for (NhanVien nv : nvList) {
            tableModel.addRow(new Object[]{
                nv.getMaNV(),
                nv.getTenNV(),
                nv.getNamSinh(),
                nv.getDiaChi(),
                nv.getThanhPho(),
                nv.getQuan(),
                nv.getPhuong(),
                nv.getTrangThai(),
                nv.getNoiDieuTri(),
                nv.getLienQuan(),
                nv.getLichSuCovid(),
            });
        }
    }
    
    public void getDataAZ(){
        nvList = NhanVienDao.getAllAZ();
        tableModel.setRowCount(0);
        for (NhanVien nv : nvList) {
            tableModel.addRow(new Object[]{
                nv.getMaNV(),
                nv.getTenNV(),
                nv.getNamSinh(),
                nv.getDiaChi(),
                nv.getThanhPho(),
                nv.getQuan(),
                nv.getPhuong(),
                nv.getTrangThai(),
                nv.getNoiDieuTri(),
                nv.getLienQuan(),
                nv.getLichSuCovid(),
            });
        }
    }
    
    public void getDataZA(){
        nvList = NhanVienDao.getAllZA();
        tableModel.setRowCount(0);
        for (NhanVien nv : nvList) {
            tableModel.addRow(new Object[]{
                nv.getMaNV(),
                nv.getTenNV(),
                nv.getNamSinh(),
                nv.getDiaChi(),
                nv.getThanhPho(),
                nv.getQuan(),
                nv.getPhuong(),
                nv.getTrangThai(),
                nv.getNoiDieuTri(),
                nv.getLienQuan(),
                nv.getLichSuCovid(),
            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnDangXuat = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTenNV = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        namSinhVar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        diaChiVar = new javax.swing.JTextField();
        trangThaiVar = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        noiDieuTriVar = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        thanhPhoVar = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        quanVar = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        phuongVar = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        lienQuanVar = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        lichSuCovidVar = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnReset1 = new javax.swing.JButton();
        sapXepVar = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhSach = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Quản lý bệnh nhân");

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/backsmall.png"))); // NOI18N
        btnBack.setText("Quay lại menu");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnDangXuat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(181, 181, 181)
                .addComponent(btnDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnBack))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setText("Mã bệnh nhân (CCCD)");

        jLabel7.setText("Tên bệnh nhân");

        jLabel8.setText("Năm sinh");

        jLabel9.setText("Địa chỉ");

        jLabel10.setText("Trạng thái");

        jLabel11.setText("Nơi điều trị");

        jLabel12.setText("Thành Phố");

        thanhPhoVar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hồ Chí Minh", "Bến Tre", "Cần Thơ", "Đà Nẵng", "Hải Phòng" }));
        thanhPhoVar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                thanhPhoVarMouseClicked(evt);
            }
        });
        thanhPhoVar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thanhPhoVarActionPerformed(evt);
            }
        });

        jLabel13.setText("Quận/Huyện");

        quanVar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quanVarActionPerformed(evt);
            }
        });

        jLabel14.setText("Phường");

        jLabel15.setText("Liên quan tới");

        jLabel16.setText("Đã từng dính");

        btnReset.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnReset.setText("Thống Kê");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(26, 26, 26)
                        .addComponent(lienQuanVar, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(32, 32, 32)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(thanhPhoVar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(namSinhVar, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(trangThaiVar, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel11))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel13)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(noiDieuTriVar, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(quanVar, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(18, 18, 18))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lichSuCovidVar, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(100, 100, 100)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(phuongVar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(diaChiVar, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                            .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(35, 35, 35))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(trangThaiVar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(namSinhVar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)
                        .addComponent(noiDieuTriVar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(diaChiVar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(thanhPhoVar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(quanVar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(phuongVar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(lienQuanVar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(lichSuCovidVar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnThem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/them.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/sua.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnTimKiem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search.png"))); // NOI18N
        btnTimKiem.setText("Tìm kiếm theo tên");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/xoa.png"))); // NOI18N
        btnXoa.setText("Xoá");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnReset1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnReset1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/reset.png"))); // NOI18N
        btnReset1.setText("Reset");
        btnReset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReset1ActionPerformed(evt);
            }
        });

        sapXepVar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "A -> Z", "Z -> A" }));
        sapXepVar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                sapXepVarItemStateChanged(evt);
            }
        });
        sapXepVar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sapXepVarMouseClicked(evt);
            }
        });
        sapXepVar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sapXepVarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sapXepVar, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(btnReset1, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                    .addGap(759, 759, 759)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sapXepVar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnReset1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        tblDanhSach.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblDanhSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CCCD", "Tên", "Năm Sinh", "Địa chỉ", "Thành Phố", "Quận", "Phường", "Trạng thái", "Nơi điều trị", "Liên Quan", "Lịch Sử Covid"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDanhSach.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblDanhSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDanhSach);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        new StaffForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        // TODO add your handling code here:
        new DangNhap().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        double countF0 = 0;
        double countF1 = 0;
        double countF2 = 0;
        double countF3 = 0;
        double countKB = 0;
        double all = 0;
        
        for (NhanVien nv : nvList) {
            if ("F0".equals(nv.getTrangThai().trim())){
                    countF0++;
            } else if("F1".equals(nv.getTrangThai().trim())){
                countF1++;
            } else if("F2".equals(nv.getTrangThai().trim())){
                countF2++;
            } else if("F3".equals(nv.getTrangThai().trim())){
                countF3++;
            } else if("Khỏi bệnh".equals(nv.getTrangThai().trim())){
                countKB++;
            }
        }
        
        all = countF0 + countF1 + countF2 + countF3 + countKB;
       
        DefaultPieDataset pieDataset = new DefaultPieDataset ();
        pieDataset.setValue("F0: " + Math.round(countF0/all *100 *100.0)/100.0 + "%", countF0);
        pieDataset.setValue("F1: " + Math.round(countF1/all *100 *100.0)/100.0 + "%", countF1);
        pieDataset.setValue("F2: " + Math.round(countF2/all *100 *100.0)/100.0 + "%", countF2);
        pieDataset.setValue("F3: " + Math.round(countF3/all *100 *100.0)/100.0 + "%", countF3);
        pieDataset.setValue("Khỏi bệnh: " + Math.round(countKB/all *100 *100.0)/100.0 + "%", countKB);
        
        
        JFreeChart chart = ChartFactory.createPieChart(      
         "Thống kê bệnh nhân !!!",   // chart title 
         pieDataset,          // data    
         true,             // include legend   
         true, 
         true);
        PiePlot P = (PiePlot)chart.getPlot();
//        P.setForegroundAlpha(TOP_ALIGNMENT);
        ChartFrame frame = new ChartFrame("Pie Chart", chart);
        frame.setVisible(true);
        frame.setSize(450, 500);
       
        
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        String trangThaiTemp = null;
        String nameTemp = null;
//        if (lienQuanVar.getText().isEmpty()){
//            trangThaiTemp = "F0";
//        }
        for (NhanVien nv : nvList) {
            if (lienQuanVar.getText().equals(nv.getMaNV().trim())){
                if ("F0".equals(nv.getTrangThai().trim())){
                    trangThaiVar.setText("F1");
                    trangThaiTemp = "F1";
                } else if("F1".equals(nv.getTrangThai().trim())){
                    trangThaiVar.setText("F2");
                    trangThaiTemp = "F2";
                } else{
                    trangThaiVar.setText("F3");
                    trangThaiTemp = "F3";
                }
            }
        }
        
        String maNV = txtMaNV.getText();
        if(maNV.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Mã CCCD không để trống");
            return;
        }
        String tenNV = txtTenNV.getText();
        if(tenNV.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Tên bệnh nhân không để trống");
            return;
        }
        
        try{
            if(checkMaNV(txtMaNV.getText())){
                NhanVien nv = new NhanVien(maNV, tenNV, namSinhVar.getText(), diaChiVar.getText(), thanhPhoVar.getSelectedItem().toString(), quanVar.getSelectedItem().toString(), phuongVar.getSelectedItem().toString(), trangThaiVar.getText(), noiDieuTriVar.getSelectedItem().toString(), lienQuanVar.getText(), "Có");
                NhanVienDao.insert(nv);
                ddList = DiaDiemDieuTriDao.getAllTen();
                
                for(String dd : ddList){
                    if(noiDieuTriVar.getSelectedItem().toString().equals(dd)){
                        DiaDiemDieuTriDao.updatePlus(dd);
                    }
                }
                
            }else{
                JOptionPane.showMessageDialog(rootPane, "Mã CCCD không được trùng");
            }
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(rootPane, "Nhập số và không để trống");
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, ex);
        }
        getData();
        txtMaNV.setEnabled(true);
        btnSua.setEnabled(false);
        btnXoa.setEnabled(false);
    }//GEN-LAST:event_btnThemActionPerformed

    private void tblDanhSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachMouseClicked
        // TODO add your handling code here:
        int row = tblDanhSach.getSelectedRow();
        if (row >= 0) {
            NhanVien nv = nvList.get(row);
            btnSua.setEnabled(true);
            btnXoa.setEnabled(true);
            txtMaNV.setEnabled(false);
//            noiDieuTriVar.setEnabled(false);
            
            txtTenNV.setText(nv.getTenNV().trim());
            txtMaNV.setText(nv.getMaNV().trim());
            namSinhVar.setText(nv.getNamSinh().trim());
            diaChiVar.setText(nv.getDiaChi().trim());
            thanhPhoVar.setSelectedItem(nv.getThanhPho().trim());
            quanVar.setSelectedItem(nv.getQuan().trim());
            phuongVar.setSelectedItem(nv.getPhuong().trim());
            trangThaiVar.setText(nv.getTrangThai().trim());
            noiDieuTriVar.setSelectedItem(nv.getNoiDieuTri().trim());
            lienQuanVar.setText(nv.getLienQuan().trim());
            lichSuCovidVar.setText(nv.getLichSuCovid().trim());
            
        }
    }//GEN-LAST:event_tblDanhSachMouseClicked

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int row = tblDanhSach.getSelectedRow();
        if (row >= 0) {
            NhanVien nv = nvList.get(row);
            int option = JOptionPane.showConfirmDialog(rootPane, "Bạn có muốn xóa không");
            if (option == 0) {
                TaiKhoanDao.delete(nv.getMaNV());
                NhanVienDao.delete(nv.getMaNV());
                ddList = DiaDiemDieuTriDao.getAllTen();
                for(String dd : ddList){
                    if(noiDieuTriVar.getSelectedItem().toString().equals(dd)){
                        DiaDiemDieuTriDao.updateMinus(dd);
                    }
                }
            }
            btnSua.setEnabled(false);
            btnXoa.setEnabled(false);
            getData();
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        String tenNV = txtTenNV.getText();
        if(tenNV.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Tên bệnh nhân không để trống");
            return;
        }

        int row = tblDanhSach.getSelectedRow();
        if (row >= 0) {
            NhanVien s = nvList.get(row);

            s.setMaNV(txtMaNV.getText().trim());
            s.setTenNV(txtTenNV.getText().trim());
            s.setNamSinh(namSinhVar.getText().trim());
            s.setDiaChi(diaChiVar.getText().trim());
            s.setThanhPho(thanhPhoVar.getSelectedItem().toString().trim());
            s.setQuan(quanVar.getSelectedItem().toString().trim());
            s.setPhuong(phuongVar.getSelectedItem().toString().trim());
            s.setTrangThai(trangThaiVar.getText().trim());
            s.setNoiDieuTri(noiDieuTriVar.getSelectedItem().toString().trim());
            s.setLienQuan(lienQuanVar.getText().trim());
            s.setLichSuCovid(lichSuCovidVar.getText().trim());
            
            nvList = NhanVienDao.getAll();
            tableModel.setRowCount(0);
            for (NhanVien nv : nvList) {
                if (nv.getMaNV().trim().equals(txtMaNV.getText())){
                    if (!noiDieuTriVar.getSelectedItem().toString().equals(nv.getNoiDieuTri())){
                    System.out.println("innn");
                    ddList = DiaDiemDieuTriDao.getAllTen();
                    for(String dd : ddList){
                        if(noiDieuTriVar.getSelectedItem().toString().equals(dd)){
                            DiaDiemDieuTriDao.update2Places(dd,nv.getNoiDieuTri());
                        }
                    }
                    }
                }
            }
//            System.out.println(noiDieuTriVar.getSelectedItem().toString());
//            System.out.println(s.getNoiDieuTri());
//            if (!noiDieuTriVar.getSelectedItem().toString().equals(s.getNoiDieuTri())){
//                System.out.println("innn");
//                ddList = DiaDiemDieuTriDao.getAllTen();
//                for(String dd : ddList){
//                    if(noiDieuTriVar.getSelectedItem().toString().equals(dd)){
//                        DiaDiemDieuTriDao.update2Places(dd,s.getNoiDieuTri());
//                    }
//                }
//            }
            NhanVienDao.update(s);
            
            
            
            getData();
            btnSua.setEnabled(false);
            btnXoa.setEnabled(false);
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        try{
            String tenNV = JOptionPane.showInputDialog(this, "Nhập tên bệnh nhân cần tìm");

            if (tenNV.equals("") == false) {
                nvList = NhanVienDao.findByTenNV(tenNV);
                tableModel.setRowCount(0);
                for (NhanVien nv : nvList) {
                    tableModel.addRow(new Object[]{
                        nv.getMaNV(),
                        nv.getTenNV(),
                        nv.getNamSinh(),
                        nv.getDiaChi(),
                        nv.getThanhPho(),
                        nv.getQuan(),
                        nv.getPhuong(),
                        nv.getTrangThai(),
                        nv.getNoiDieuTri(),
                        nv.getLienQuan(),
                        nv.getLichSuCovid(),
                    });
                }
            } else {
                getData();
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, "Không tìm thấy!");
        }
        
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void thanhPhoVarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thanhPhoVarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_thanhPhoVarMouseClicked
DefaultComboBoxModel model;
    private void thanhPhoVarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thanhPhoVarActionPerformed
        // TODO add your handling code here:
        
        if (thanhPhoVar.getSelectedItem().toString() == "Hồ Chí Minh"){
            String tp1[] = { "Quận 1", "Quận 2", "Quận 3", "Quận 4", "Quận 5" };
            model = new DefaultComboBoxModel(tp1);
            quanVar.setModel(model);
        } else if(thanhPhoVar.getSelectedItem().toString() == "Bến Tre"){
            String tp1[] = { "Huyện Bình Đại", "Huyện Châu Thành", "Huyện Giồng Trôm", "Huyện Ba Tri", "Huyện Chợ Lách" };
            model = new DefaultComboBoxModel(tp1);
            quanVar.setModel(model);
        } else if(thanhPhoVar.getSelectedItem().toString() == "Cần Thơ"){
            String tp1[] = { "Quận Ninh Kiều", "Quận Bình Thuỷ", "Quận Cái Răng", "Quận Ô Môn", "Huyện Phong Điền" };
            model = new DefaultComboBoxModel(tp1);
            quanVar.setModel(model);
        } else if(thanhPhoVar.getSelectedItem().toString() == "Đà Nẵng"){
            String tp1[] = { "Quận Cẩm Lệ", "Quận Hải Châu", "Quận Liên Chiểu", "Quận Ngũ Hành Sơn", "Quận Sơn Trà" };
            model = new DefaultComboBoxModel(tp1);
            quanVar.setModel(model);
        } else if(thanhPhoVar.getSelectedItem().toString() == "Hải Phòng"){
            String tp1[] = { "Quận Hồng Bàng", "Quận Lê Chân", "Quận Ngô Quyền", "Quận Kiến An", "Quận Hải An" };
            model = new DefaultComboBoxModel(tp1);
            quanVar.setModel(model);
        }
    }//GEN-LAST:event_thanhPhoVarActionPerformed

    private void quanVarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quanVarActionPerformed
        // TODO add your handling code here:
        if (thanhPhoVar.getSelectedItem().toString() == "Hồ Chí Minh"){
                String q1[] = { "Bến Nghé", "Bến Thành", "Cô Giang", "Cầu Kho", "Đa Kao" };
                model = new DefaultComboBoxModel(q1);
                phuongVar.setModel(model);
        } else if (thanhPhoVar.getSelectedItem().toString() == "Bến Tre"){
                String q1[] = { "An Phú", "Thảo Điền", "An Khánh", "Bình Khánh", "Bình An" };
                model = new DefaultComboBoxModel(q1);
                phuongVar.setModel(model);
        } else if (thanhPhoVar.getSelectedItem().toString() == "Cần Thơ"){
                String q1[] = { "Phường 1", "Phường 2", "Phường 3", "Phường 4", "Phường 5" };
                model = new DefaultComboBoxModel(q1);
                phuongVar.setModel(model);
        } else if (thanhPhoVar.getSelectedItem().toString() == "Đà Nẵng"){
                String q1[] = { "Phường 1", "Phường 2", "Phường 3", "Phường 4", "Phường 5" };
                model = new DefaultComboBoxModel(q1);
                phuongVar.setModel(model);
        } else if (thanhPhoVar.getSelectedItem().toString() == "Hải Phòng"){
                String q1[] = { "Phường 1", "Phường 2", "Phường 3", "Phường 4", "Phường 5" };
                model = new DefaultComboBoxModel(q1);
                phuongVar.setModel(model);
        } 
        
    }//GEN-LAST:event_quanVarActionPerformed

    private void btnReset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReset1ActionPerformed
        // TODO add your handling code here:
        txtMaNV.setEnabled(true);
        noiDieuTriVar.setEnabled(true);
        namSinhVar.setText("");
        trangThaiVar.setText("");
        txtTenNV.setText("");
        noiDieuTriVar.setSelectedItem("Bệnh viện Chợ Rẫy");
        diaChiVar.setText("");
        thanhPhoVar.setSelectedItem("Hồ Chí Minh");
        quanVar.setSelectedItem("");
        phuongVar.setSelectedItem("");
        lienQuanVar.setText("");
        lichSuCovidVar.setText("");
        txtMaNV.setText("");
        
        nvList = NhanVienDao.getAll();
        tableModel.setRowCount(0);
        for(int i = 0; i < 10; i++){
            for (NhanVien nv : nvList) {
                if (nv.getLienQuan().trim().equals("") && !nv.getTrangThai().trim().equals("Khỏi bệnh")){
                    NhanVienDao.updateF("F0", nv.getMaNV());
                } else{
                    System.out.println("A");
                    for (NhanVien nv2 : nvList){
                        if (nv.getLienQuan().trim().equals(nv2.getMaNV().trim())){
                            System.out.println(nv2.getMaNV().trim());
                            if(nv2.getTrangThai().trim().equals("F0")){
                                NhanVienDao.updateF("F1", nv.getMaNV());
                                nv.setTrangThai("F1");
                            } else if(nv2.getTrangThai().trim().equals("F1")){
                                NhanVienDao.updateF("F2", nv.getMaNV());
                                nv.setTrangThai("F2");
                            } else if(nv2.getTrangThai().trim().equals("F2")){
                                NhanVienDao.updateF("F3", nv.getMaNV());
                                nv.setTrangThai("F3");
                            }
                        }
                    }
                }
            }
            getData();
        }
        
        
        
    }//GEN-LAST:event_btnReset1ActionPerformed

    private void sapXepVarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sapXepVarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_sapXepVarMouseClicked

    private void sapXepVarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sapXepVarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sapXepVarActionPerformed

    private void sapXepVarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_sapXepVarItemStateChanged
        // TODO add your handling code here:
        String item = (String) evt.getItem();
        if (evt.getStateChange() == ItemEvent.SELECTED) {
                System.out.println(item);
                switch (item) {
                    case "All":
                        getData();
                        break;
                    case "A -> Z":
                        getDataAZ();
                        break;
                    case "Z -> A":
                        getDataZA();
                        break;
                }
        }
        
    }//GEN-LAST:event_sapXepVarItemStateChanged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        ddList = DiaDiemDieuTriDao.getAllTen();
        model = new DefaultComboBoxModel(ddList.toArray());
        noiDieuTriVar.setModel(model);
    }//GEN-LAST:event_formWindowOpened
    private boolean checkMaNV(String maNV){
        for(NhanVien nv : nvList){
            if(nv.getMaNV().trim().equalsIgnoreCase(maNV.trim())){
                return false;
            }
        }
        return true;
    }
    
    public void checkAddress(){
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
                /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyNhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnReset1;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JTextField diaChiVar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lichSuCovidVar;
    private javax.swing.JTextField lienQuanVar;
    private javax.swing.JTextField namSinhVar;
    private javax.swing.JComboBox<String> noiDieuTriVar;
    private javax.swing.JComboBox<String> phuongVar;
    private javax.swing.JComboBox<String> quanVar;
    private javax.swing.JComboBox<String> sapXepVar;
    private javax.swing.JTable tblDanhSach;
    private javax.swing.JComboBox<String> thanhPhoVar;
    private javax.swing.JTextField trangThaiVar;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtTenNV;
    // End of variables declaration//GEN-END:variables
}
